# Generated by Django 5.2.8 on 2025-11-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время тренировки')),
                ('available_slots', models.IntegerField(verbose_name='Количество доступных мест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trainers.trainer', verbose_name='Тренер')),
                ('workout_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.workoutclass', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['datetime'],
                'indexes': [models.Index(fields=['workout_class', 'datetime'], name='schedule_sc_workout_5d7083_idx')],
            },
        ),
    ]
