# Generated by Django 5.2.8 on 2025-11-22 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_sc_workout_5d7083_idx',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available_slots',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Количество доступных мест'),
        ),
    ]
