# Generated by Django 5.2.8 on 2025-11-22 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_remove_schedule_schedule_sc_workout_5d7083_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ФИО может содержать только буквы и пробелы', regex='^[а-яА-ЯёЁa-zA-Z\\s]+$')], verbose_name='ФИО участника')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999' или '89999999999'", regex='^\\+?7?\\d{10}$')], verbose_name='Номер телефона участника')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Введите корректный email адрес', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Почта участника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Запись на тренировку',
                'verbose_name_plural': 'Записи на тренировки',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'schedule')},
            },
        ),
    ]
