# Generated by Django 5.2.8 on 2025-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта участника'),
        ),
    ]
